apiVersion: v1
kind: Service
metadata:
  name: ticket-reservation-api
  labels:
    app: ticket-reservation-api
spec:
  type: NodePort
  selector:
    app: ticket-reservation-api
  ports:
    - name: http
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-reservation-api
  labels:
    name: ticket-reservation-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ticket-reservation-api
  template:
    metadata:
      labels:
        app: ticket-reservation-api
    spec:
      containers:
        - name: api
          image: dvmflstm/ticket_reservation_api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: R2DBC_LOGGING_LEVEL
              value: "DEBUG"
            - name: SPRING_R2DBC_URL
              value: "r2dbc:mysql://mysql:3306/ticket_reservation?useUnicode=true&characterEncoding=utf8"
            - name: SPRING_R2DBC_USERNAME
              value: "root"
            - name: SPRING_R2DBC_PASSWORD
              value: "dkdltm123"
            - name: REDIS_URI
              value: "redis://ticket-reservation-redis:6379"